### ISSUE TITLE
centrifuge/auth/

### ISSUE THREAD

**Issue by vlordier** [synw/django-instant#3]
I'm getting an error 500 from `centrifuge.js`    
```
 setTimeout(function() {
        // method == 'get' ? self.xhr.send() : self.xhr.send(JSON.stringify(ops.data));
        xhr.send(JSON.stringify(data));
    }, 20);
    return xhr;
};
```
Running centrifugo and getting correct :  
`New SockJS session established with uid bf3add4a-4887-4c7b-a4f2-82f08429ee9f`
Could I have missed something in the setup ?

**Comment by synw** [comment]
Could you please provide the response with the error message of this 500? What were you trying to do exactly? I need to know in what context this error occured

Tip: you can use the setting `INSTANT_DEBUG = True` to debug the javascript.

Be sure to set the urls for /centrifuge/auth/

**Comment by vlordier** [comment]
I am getting a 404 raised by    `instant.views.instant_auth` when I try to get `http://127.0.0.1:8000/centrifuge/auth/`

added to main `url.py`

```
from instant.views import instant_auth

urlpatterns = [
     # ...
     url(r'^centrifuge/auth/$', instant_auth, name='instant-auth'),
     ]

```

Added django-presence and included 

```
                {% include "presence/js/handlers.js" %}
                {% include "presence/js/client.js" %}

```

in my template

Unsure how this url should be setup ?

**Comment by synw** [comment]
The 404 is normal because this page can only be accessed via ajax calls. It returns a json response.

For the urls the doc is here: http://django-instant.readthedocs.io/en/latest/src/private_chans.html#private-channels : you must also enable the private channels for them to work, all the doc is in this page on how to do it.

Note that you need access to /centrifuge/auth/ only if you are using private channels.

For presence include `{% include "presence/js/handlers.js" %}` in `instant/extra_handlers.js` and `{% include "presence/js/client.js" %}` in `instant/extra_clients.js` as mentioned in the presence doc: you can not include this anywhere, as it is part of a bigger peace of code and it needs to be included in the right place.

Edit: to be sure /centrifugo/auth/ responds setup a private channel and add the settings `INSTANT_DEBUG = True` to settings.py:  this will print the json return value in the browser's console.

**Comment by vlordier** [comment]
The actual error is this :

```
Internal Server Error: /centrifuge/auth/
Traceback (most recent call last):
  File "(path)/lib/python3.4/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "(path)/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "(path)/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "(path)/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "(path)/lib/python3.4/site-packages/instant/views.py", line 22, in instant_auth
    data = json.loads(request.body)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[31/Oct/2016 12:58:02] "POST /centrifuge/auth/ HTTP/1.1" 500 16461
```

I will try to fix it to present a proper JSON to the AJAX call.

**Comment by vlordier** [comment]
Got it : 
`data = json.loads(request.body)` line 22 in `instant/views.py`
should be 
`data = json.loads(request.body.decode("utf-8"))`
=> /centriguge/auth returns HTTP 200 now

**Comment by synw** [comment]
I did the correction in the version 0.2.1

Thanks for your help!
