### ISSUE TITLE
Support the Centrifugo Redis API

### ISSUE THREAD

**Issue by synw** [synw/django-instant#8]
- [ ] Implement a way to use the [Centrifugo Redis API](https://fzambia.gitbooks.io/centrifugal/content/server/engines.html#redis-engine)

**Comment by FZambia** [comment]
Hi, this won't be supported in Centrifugo v2. The reason is that when publish over Redis queue you can't properly handle errors – you never know was message successfully processed by Centrifugo worker or not. This is also hard to reason about timeouts in this case. This can lead to messages delivered in arbitrary time in future. In practice this works pretty good in normal conditions but can result in strange behaviour in stress situations.

**Comment by synw** [comment]
Got ir. So this feature will not be implemented then. Thanks for the info and good luck for the v2 stabilization process. We will update to v2 here when it will be stable
